// Copyright (c) Athena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom Script Commands
 * Place the definition of custom script commands in this file.
 * Format:
 *	BUILDIN_DEF(command_name,"parameters"),
 **/

//BUILDIN_DEF(example,""),

BUILDIN_DEF(uniteffect,"ii?"), //[kuku]
BUILDIN_DEF2(uniteffect,"mobeffect","ii?"), //kuku
BUILDIN_DEF(unitremove, "i?"),//[╰づ记忆•斑驳〤]
BUILDIN_DEF(getareagid, "si*"),//[╰づ记忆•斑驳〤]
BUILDIN_DEF(script4each, "si*"), //[kuku]